version: "3"
services:
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile-nginx
        image: nginx:v4
        ports:
            - "3535:80"
    rest_server:
        build: ./backend/rest_server
        image: ${APP}:${IMAGE_VERSION}
        user: ${APP_USER}
        ports:
            - "${HOST_PORT}:${REST_SERVER_PORT}"
        volumes:
            - ${HOST_RESULTS_DIR_PREFIX}${ROOT_RESULTS_DIR}:${ROOT_RESULTS_DIR}
        command: bash -c "FLASK_APP=/app/rest_server.py FLASK_DEBUG=true python3 rest_server.py"
    emscripten:
        build: ./backend/emscripten
        image: ${EMSCRIPTEN}:${IMAGE_VERSION}
        user: ${APP_USER}
        volumes:
            - ${HOST_RESULTS_DIR_PREFIX}${ROOT_RESULTS_DIR}${EMSCRIPTEN}:${ROOT_RESULTS_DIR}${EMSCRIPTEN}
        stdin_open: true
        tty: true
        command: /bin/bash
