version: "3"
services:
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8000:8080"
    ucrm_db:
        build:
            context: ./backend/database
            dockerfile: Dockerfile
        image: ucrm_db:${IMAGE_VERSION}
        container_name: ucrm_db
        user: postgres
        environment:
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=database
        volumes:
            - "${HOST_RESULTS_DIR_PREFIX}/wasmcc_volumes/database_volume:/var/lib/postgresql/data"
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        image: angular_cli:${IMAGE_VERSION}
        container_name: angular_cli
        environment:
            - API_URL=http://${SYSTEM_IP}:${BACKEND_HOST_PORT}
        ports:
            - "${FRONTEND_HOST_PORT}:4200"
        volumes:
            - "/home/nikos/HMMY\ EMP/Diploma\ Thesis/Webassembly_Compiler_Collection/frontend/app-frontend:/home/node/app-frontend"
        command: bash -c "ng serve --host 0.0.0.0"
    rest_server:
        build: ./backend/rest_server
        image: rest_server:${IMAGE_VERSION}
        user: server
        container_name: wasmcc
        environment:
            - SYSTEM_IP=${SYSTEM_IP}
            - HOST_FRONTEND_ADDRESS=${SYSTEM_IP}:${FRONTEND_HOST_PORT}
            - UPLOAD_PATH_EMSCRIPTEN=${ROOT_RESULTS_DIR}/${EMSCRIPTEN}
            - UPLOAD_PATH_GOLANG=${ROOT_RESULTS_DIR}/${GOLANG}/src
            - GOOS=js
            - GOARCH=wasm
            - GOCACHE=${ROOT_RESULTS_DIR}/${GOLANG}/dev_tools/.cache/go-build
            - GOENV=${ROOT_RESULTS_DIR}/${GOLANG}/dev_tools/.config/go/env
            - GO_INSTALLATION_PATH=/usr/local/go/
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=database
            - JWT_SECRET_KEY=jwt_secret_key
        ports:
            - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
        volumes:
            - "./backend/rest_server:/app"
            - "${HOST_RESULTS_DIR_PREFIX}/wasmcc_results${ROOT_RESULTS_DIR_DEVEL}:/results"
        command: bash -c "until python database_accepts_connections.py; do sleep 5; done; FLASK_APP=/app/wsgi.py FLASK_ENV=development python3 /app/wsgi.py"
        depends_on:
            - ucrm_db
