version: "3"
services:
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        image: angular_cli:${IMAGE_VERSION}
        container_name: angular_cli_devel
        ports:
            - "${FRONTEND_HOST_PORT}:4200"
        volumes:
            - "/home/nikos/HMMY\ EMP/Diploma\ Thesis/Webassembly_Compiler_Collection/frontend/app-frontend:/home/node/app-frontend"
        command: bash -c "ng serve --host 0.0.0.0"
    rest_server:
        build: ./backend/rest_server
        image: ${APP}-devel:${IMAGE_VERSION}
        user: ${APP_USER}
        container_name: wasmcc-devel
        environment:
            - UPLOAD_PATH_EMSCRIPTEN=${ROOT_RESULTS_DIR}/${EMSCRIPTEN}/
        ports:
            - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
        volumes:
            - "./backend/rest_server:/app"
            - "${HOST_RESULTS_DIR_PREFIX}${ROOT_RESULTS_DIR}:${ROOT_RESULTS_DIR}"
        command: bash -c "FLASK_APP=/app/rest_server.py FLASK_ENV=development python3 /app/rest_server.py"
