version: "3"
services:
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile-nginx
        image: nginx:v4
        ports:
            - "3535:80"
    rest_server:
        build: ./backend/rest_server
        image: ${APP}:${IMAGE_VERSION}
        user: ${APP_USER}
        ports:
            - "${HOST_PORT}:${REST_SERVER_PORT}"
        volumes:
            - "./backend/rest_server/rest_server.py:/app/rest_server.py"
            - ${HOST_RESULTS_DIR_PREFIX}${ROOT_RESULTS_DIR}:${ROOT_RESULTS_DIR}
        command: bash -c "FLASK_APP=/app/rest_server.py FLASK_ENV=development python3 /app/rest_server.py"
