version: "3"
services:
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile-nginx
        image: nginx:${IMAGE_VERSION}
        container_name: nginx
        ports:
            - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
            - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
        depends_on:
            - rest_server
    rest_server:
        build: ./backend/rest_server
        image: ${APP}:${IMAGE_VERSION}
        user: ${APP_USER}
        container_name: wasmcc
        environment:
            - UPLOAD_PATH_EMSCRIPTEN=${ROOT_RESULTS_DIR}/${EMSCRIPTEN}/
        expose:
            - ${BACKEND_CONTAINER_PORT}
        volumes:
            - "${HOST_RESULTS_DIR_PREFIX}${ROOT_RESULTS_DIR}:${ROOT_RESULTS_DIR}"
        command: bash -c "uwsgi --ini /app/uwsgi.ini"
