version: "3"
services:
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8000:8080"
    ucrm_db:
        build:
            context: ./backend/database
            dockerfile: Dockerfile
        image: ucrm_db:${IMAGE_VERSION}
        container_name: ucrm_db
        user: postgres
        environment:
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=database
        volumes:
            - "${HOST_RESULTS_DIR_PREFIX}/wasmcc_volumes/database_volume_prod:/var/lib/postgresql/data"
    nginx:
        build:
            context: ./frontend/
            dockerfile: Dockerfile-nginx
        image: nginx:${IMAGE_VERSION}
        container_name: nginx
        environment:
            - API_URL=http://${SYSTEM_IP}:${BACKEND_HOST_PORT}
        user: nginx
        ports:
            - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
            - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
        command: bash -c "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && nginx -g 'daemon off;'"
        depends_on:
            - rest_server
    rest_server:
        build: ./backend/rest_server
        image: rest_server:${IMAGE_VERSION}
        user: server
        container_name: wasmcc
        environment:
            - SYSTEM_IP=${SYSTEM_IP}
            - HOST_FRONTEND_ADDRESS=${SYSTEM_IP}:${FRONTEND_HOST_PORT}
            - UPLOAD_PATH_EMSCRIPTEN=${ROOT_RESULTS_DIR}/${EMSCRIPTEN}/
            - UPLOAD_PATH_GOLANG=${ROOT_RESULTS_DIR}/${GOLANG}/src/
            - GOOS=js
            - GOARCH=wasm
            - GOCACHE=${ROOT_RESULTS_DIR}/${GOLANG}/dev_tools/.cache/go-build
            - GOENV=${ROOT_RESULTS_DIR}/${GOLANG}/dev_tools/.config/go/env
            - GO_INSTALLATION_PATH=/usr/local/go/
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=database
            - JWT_SECRET_KEY=jwt_secret_key
        expose:
            - ${BACKEND_CONTAINER_PORT}
        volumes:
            - "${HOST_RESULTS_DIR_PREFIX}/wasmcc_results${ROOT_RESULTS_DIR}:/results"
        command: bash -c "until python database_accepts_connections.py; do sleep 5; done; uwsgi --ini /app/uwsgi.ini"
        depends_on:
            - ucrm_db
